package mock

const Mock = "// Code generated by mockgen. DO NOT EDIT."
const Mock1 = "// Code generated by mockgen. DO NOT EDIT.1"
const Mock2 = "// Code generated by mockgen. DO NOT EDIT.2"
const Mock3 = "// Code generated by mockgen. DO NOT EDIT.2"
const Mock4 = "// Code generated by mockgen. DO NOT EDIT.3"
